version: '3.7'

services:
  database:
    image: postgres:16-alpine
    ports:
      - 5432:5432
    volumes:
      - ./postgresData:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}